dromara:
  x-file-storage: #文件存储配置
    default-platform: minio-1 #默认使用的存储平台
    thumbnail-suffix: ".min.jpg" #缩略图后缀，例如【.min.jpg】【.png】
    #对应平台的配置写在这里，注意缩进要对齐
    minio:
      - platform: minio-1 # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: admin
        secret-key: admin123
        end-point: "http://127.0.0.1:9000/"
        bucket-name: dev
        domain: "http://127.0.0.1:9000/dev/" # 访问域名，注意“/”结尾，例如：http://minio.abc.com/abc/
#        base-path: test/ # 基础路径